version: '3.1'

services:
  web:
    # If we want to use a pre-built image, use this instead and comment out the below build step
    #image: store-website:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
